[versions]
composeMultiplatform = "1.9.0-rc01"
kotlin = "2.2.10"
kotlinx-coroutines = "1.10.2"
composeMaterial3 = "1.9.0-alpha04"

[libraries]
kotlinx-coroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
compose-material3-expressive = { group = "org.jetbrains.compose.material3", name = "material3", version.ref = "composeMaterial3" }

[plugins]
composeHotReload = { id = "org.jetbrains.compose.hot-reload", version = "1.0.0-beta06" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }